import { LayoutDashboard, Users } from 'lucide-react';

const IMG = {
  kanban: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/44bb39e76_generated_image.png',
  drivers: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/fa0bfb7cb_generated_image.png',
};

export const GUIDE_SECTIONS = [
  {
    id: 'dashboard',
    icon: LayoutDashboard,
    image: IMG.kanban,
    en: {
      title: 'Dispatch Dashboard',
      tagline: 'Command center for real-time operations',
      description: 'The Dashboard is your operational hub. It features a live Kanban board, stat cards, fleet sidebar, map view, filter bar, and action buttons for creating orders and managing deliveries.',
      steps: [
        { title: 'Read the Stat Cards', desc: 'At the top of the Dashboard, four stat cards summarize your operation: Total Orders, Active Deliveries (New + Assigned + In Progress), Trucks Available, and Today Delivered. These update in real time as data changes.' },
        { title: 'Read the Kanban Board', desc: 'Orders flow left to right across four columns with color-coded top borders: New (orange) → Assigned (blue) → In Progress (amber) → Delivered (green). Each card shows the order number, company, location, mix type, volume, assigned truck plate + driver, and scheduled time.' },
        { title: 'Watch ETA Countdowns', desc: 'In-progress order cards display an amber ETA countdown timer showing time remaining until expected delivery, based on historical average delivery times for that location. If overdue, the timer turns red.' },
        { title: 'Create a New Order', desc: 'Click the "New Order" button (orange, top-left). Fill in the company, delivery location, mix type, volume, priority, and scheduled time, then click "Create". The order appears in the New column instantly.' },
        { title: 'Assign a Truck & Driver', desc: 'Click any order card to open the detail modal. In the Assignment section, select an available truck and driver from the dropdowns, then click "Assign". The order moves to the "Assigned" column and the truck status changes to "Loading".' },
        { title: 'Broadcast to WhatsApp', desc: 'In the order detail or new order modal, click "Broadcast to Drivers". Select a driver group, and the system simulates a WhatsApp group chat. The first driver to reply "YES" is automatically assigned.' },
        { title: 'Start Delivery', desc: 'Once assigned, click "Start Delivery" in the order detail modal to move the order to "In Progress". This records the departure time, sets the truck status to "In Transit", and starts the ETA countdown.' },
        { title: 'Mark as Delivered', desc: 'Open an in-progress order and click "Mark Delivered" to complete it. For batch confirmation, use the checkbox in the top-right corner of each card to select multiple orders, then click "Mark Delivered" in the green bulk-action bar that appears.' },
        { title: 'Use Demo Mode', desc: 'Toggle "Demo Mode" (violet button, top-right) to auto-progress orders every 6 seconds. It auto-assigns new orders, advances assigned → in-progress, and completes in-progress → delivered. Perfect for presentations and training — a violet banner confirms it is active.' },
        { title: 'Simulate WhatsApp Order', desc: 'Click the "Simulate Client WhatsApp" button (chat icon) to generate a random incoming order as if a client sent it via WhatsApp. Requires at least one company and location to exist.' },
        { title: 'Simulate Driver Reply', desc: 'Click the "Simulate Driver Reply" button (reply icon) to auto-assign the first new order to a random available truck and driver — as if a driver replied "YES" to a broadcast.' },
        { title: 'Filter the Board', desc: 'Use the filter bar below the stat cards: click status chips (All, Active, New, Assigned, In Progress, Delivered) with live order counts, or use the Truck and Company dropdowns to narrow further. Click "Clear" to reset all filters.' },
        { title: 'Check the Fleet Sidebar', desc: 'On the right side of the board, the Truck & Driver sidebar shows a live summary of all trucks and drivers with their current status. Use it to see who is available before assigning.' },
        { title: 'View the Active Map', desc: 'Below the Kanban board, the map placeholder shows the location of active trucks. This gives a geographic overview of your fleet in transit.' },
      ],
      tips: 'Urgent orders appear with a red "URGENT" badge and a warning triangle icon. Use the priority flag when creating orders to surface critical deliveries at the top of each column.',
    },
    es: {
      title: 'Panel de Despacho',
      tagline: 'Centro de comando para operaciones en tiempo real',
      description: 'El Panel es su centro operativo. Cuenta con un tablero Kanban en vivo, tarjetas de estadísticas, barra lateral de flota, vista de mapa, barra de filtros y botones de acción para crear pedidos y gestionar entregas.',
      steps: [
        { title: 'Lea las Tarjetas de Estadísticas', desc: 'En la parte superior del Panel, cuatro tarjetas resumen su operación: Total de Pedidos, Entregas Activas (Nuevas + Asignadas + En Progreso), Camiones Disponibles y Entregados Hoy. Se actualizan en tiempo real.' },
        { title: 'Lea el Tablero Kanban', desc: 'Los pedidos fluyen de izquierda a derecha en cuatro columnas con bordes superiores de color: Nuevo (naranja) → Asignado (azul) → En Progreso (ámbar) → Entregado (verde). Cada tarjeta muestra número, empresa, ubicación, mezcla, volumen, placa del camión + conductor y hora.' },
        { title: 'Vea los Contadores ETA', desc: 'Las tarjetas en progreso muestran un contador ETA ámbar con el tiempo restante hasta la entrega esperada, basado en tiempos históricos de esa ubicación. Si está vencido, el contador se pone rojo.' },
        { title: 'Cree un Pedido Nuevo', desc: 'Haga clic en "Nuevo Pedido" (naranja, arriba a la izquierda). Complete empresa, ubicación, tipo de mezcla, volumen, prioridad y hora programada, luego haga clic en "Crear".' },
        { title: 'Asigne Camión y Conductor', desc: 'Haga clic en cualquier tarjeta para abrir el modal de detalle. En la sección de Asignación, seleccione un camión y conductor disponibles, luego haga clic en "Asignar". El pedido pasa a "Asignado" y el camión a "Cargando".' },
        { title: 'Transmita por WhatsApp', desc: 'En el modal de detalle o nuevo pedido, haga clic en "Transmitir a Conductores". Seleccione un grupo y el sistema simula un chat de WhatsApp. El primer conductor en responder "SÍ" es asignado automáticamente.' },
        { title: 'Inicie la Entrega', desc: 'Una vez asignado, haga clic en "Iniciar Entrega" para mover el pedido a "En Progreso". Esto registra la hora de salida, cambia el camión a "En Tránsito" e inicia el contador ETA.' },
        { title: 'Marque como Entregado', desc: 'Abra un pedido en progreso y haga clic en "Marcar Entregado". Para confirmación masiva, use la casilla en la esquina superior derecha de cada tarjeta para seleccionar múltiples pedidos, luego haga clic en "Marcar Entregado" en la barra verde que aparece.' },
        { title: 'Use el Modo Demo', desc: 'Active "Modo Demo" (botón violeta, arriba a la derecha) para progresar pedidos automáticamente cada 6 segundos. Asigna pedidos nuevos, avanza asignados → en progreso, y completa en progreso → entregado. Ideal para presentaciones.' },
        { title: 'Simule Pedido WhatsApp', desc: 'Haga clic en "Simular WhatsApp Cliente" (icono de chat) para generar un pedido aleatorio entrante como si un cliente lo enviara por WhatsApp. Requiere al menos una empresa y ubicación.' },
        { title: 'Simule Respuesta de Conductor', desc: 'Haga clic en "Simular Respuesta Conductor" (icono de respuesta) para auto-asignar el primer pedido nuevo a un camión y conductor disponibles aleatorios.' },
        { title: 'Filtre el Tablero', desc: 'Use la barra de filtros bajo las tarjetas: haga clic en las fichas de estado (Todos, Activos, Nuevos, Asignados, En Progreso, Entregados) con conteos en vivo, o use los menús de Camión y Empresa. Haga clic en "Limpiar" para reiniciar.' },
        { title: 'Revise la Barra Lateral', desc: 'A la derecha del tablero, la barra lateral de Camiones y Conductores muestra un resumen en vivo de todos los camiones y conductores con su estado actual.' },
        { title: 'Vea el Mapa Activo', desc: 'Bajo el tablero Kanban, el mapa muestra la ubicación de los camiones activos. Da una visión geográfica de su flota en tránsito.' },
      ],
      tips: 'Los pedidos urgentes aparecen con una insignia roja "URGENT" y un icono de triángulo de advertencia. Use la bandera de prioridad al crear pedidos para resaltar entregas críticas.',
    },
  },
  {
    id: 'drivers',
    icon: Users,
    image: IMG.drivers,
    en: {
      title: 'Driver Management',
      tagline: 'Workforce visibility and compensation in one place',
      description: 'Track every driver — employees and contractors — with availability status, compensation rates, and license expiry tracking. The Drivers page displays all drivers in a searchable table with inline edit and delete actions.',
      steps: [
        { title: 'Understand the Table Layout', desc: 'The table has columns: Name, Cédula, Phone (hidden on mobile), Type, Availability, Rate/Hour (hidden on small screens), Rate/Order (hidden on small screens), and Actions. Responsive column hiding keeps the table readable on any device.' },
        { title: 'Search for a Driver', desc: 'Use the search bar (top-right, below the page title) to find drivers by name or cédula number. Search filters the table in real time as you type.' },
        { title: 'Add a Driver', desc: 'Click "Add New" (orange button, top-right). In the dialog, enter: full name, cédula (national ID), phone number, type (Employee or Contractor), availability, compensation rates, OT multiplier, and license expiry. Only Admins can create drivers.' },
        { title: 'Set Compensation Rates', desc: 'In the driver form, configure Rate/Hour, Rate/Order, and Rate/Km independently per driver. Set a secondary rate multiplier (e.g. 1.5×) for overtime calculations. These rates feed into the Compensation Calculator when orders are delivered.' },
        { title: 'Track Availability', desc: 'Drivers have four states with color-coded badges: Available (green), On Route (amber), Off Duty (gray), and Vacation (purple). Availability updates automatically as orders are assigned and completed on the Dashboard.' },
        { title: 'Differentiate Employee vs Contractor', desc: 'The Type column shows a blue "Employee" badge or orange "Contractor" badge. Employees typically use hourly rates; contractors may use per-order or per-km rates.' },
        { title: 'Edit a Driver', desc: 'Click the pencil icon in the Actions column to open the edit dialog. All fields are pre-filled with the driver\'s current data. Only Admins can edit drivers.' },
        { title: 'Delete a Driver', desc: 'Click the trash icon in the Actions column to remove a driver. Only Admins can delete. Exercise caution — deleted drivers cannot be recovered.' },
        { title: 'Monitor License Expiry', desc: 'Store each driver\'s license expiry date in the form. Check regularly to avoid compliance risk — expired licenses should be renewed before the driver returns to active duty.' },
      ],
      tips: 'When calculating compensation from an order\'s detail modal, the system auto-fills driver and order data when an order is marked delivered. Admins can override the calculated amount with a note.',
    },
    es: {
      title: 'Gestión de Conductores',
      tagline: 'Visibilidad de fuerza laboral y compensación en un solo lugar',
      description: 'Rastree cada conductor — empleados y contratistas — con estado de disponibilidad, tarifas de compensación y seguimiento de vencimiento de licencia. La página de Conductores muestra todos los conductores en una tabla buscable con acciones de editar y eliminar.',
      steps: [
        { title: 'Comprenda la Tabla', desc: 'La tabla tiene columnas: Nombre, Cédula, Teléfono (oculto en móvil), Tipo, Disponibilidad, Tarifa/Hora (oculto en pantallas pequeñas), Tarifa/Pedido (oculto en pantallas pequeñas) y Acciones.' },
        { title: 'Busque un Conductor', desc: 'Use la barra de búsqueda (arriba a la derecha, bajo el título) para encontrar conductores por nombre o cédula. El filtro se aplica en tiempo real mientras escribe.' },
        { title: 'Agregue un Conductor', desc: 'Haga clic en "Agregar" (botón naranja, arriba a la derecha). En el diálogo, ingrese: nombre, cédula, teléfono, tipo (Empleado o Contratista), disponibilidad, tarifas, multiplicador de horas extra y vencimiento de licencia. Solo los Administradores pueden crear conductores.' },
        { title: 'Configure Tarifas', desc: 'En el formulario, configure Tarifa/Hora, Tarifa/Pedido y Tarifa/Km independientemente por conductor. Establezca un multiplicador secundario (ej. 1.5×) para horas extra. Estas tarifas alimentan la Calculadora de Compensación.' },
        { title: 'Rastree Disponibilidad', desc: 'Los conductores tienen cuatro estados con insignias de color: Disponible (verde), En Ruta (ámbar), Fuera de Servicio (gris) y Vacaciones (morado). La disponibilidad se actualiza automáticamente al asignar y completar pedidos.' },
        { title: 'Diferencie Empleado vs Contratista', desc: 'La columna Tipo muestra una insignia azul "Empleado" o naranja "Contratista". Los empleados usan tarifa por hora; los contratistas pueden usar tarifa por pedido o por km.' },
        { title: 'Edite un Conductor', desc: 'Haga clic en el icono de lápiz en la columna Acciones para abrir el diálogo de edición. Todos los campos se pre-llenan con los datos actuales. Solo los Administradores pueden editar.' },
        { title: 'Elimine un Conductor', desc: 'Haga clic en el icono de papelera en la columna Acciones para eliminar un conductor. Solo los Administradores pueden eliminar. Tenga precaución — los conductores eliminados no pueden recuperarse.' },
        { title: 'Monitoree Vencimiento de Licencia', desc: 'Almacene la fecha de vencimiento de la licencia en el formulario. Revise regularmente para evitar riesgos de cumplimiento.' },
      ],
      tips: 'Al calcular compensación desde el modal de detalle del pedido, el sistema pre-completa los datos del conductor y pedido al marcar una entrega como completada. Los Administradores pueden ajustar el monto con una nota.',
    },
  },
];