import {
  LayoutDashboard, Package, Truck, Users, Building2, MapPin,
  BarChart2, UserCog, Settings, Shield, HelpCircle, Rocket
} from 'lucide-react';

const IMG = {
  kanban: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/44bb39e76_generated_image.png',
  analytics: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/7da381fa5_generated_image.png',
  fleet: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/ff752f7ef_generated_image.png',
  mobile: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/39b586367_generated_image.png',
  orderModal: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/d95a8d684_generated_image.png',
  drivers: 'https://media.base44.com/images/public/6a259944a41a61050894e45e/fa0bfb7cb_generated_image.png',
  companies: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1200&q=80',
  locations: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?w=1200&q=80',
  settings: 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&q=80',
  groups: 'https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=1200&q=80',
  hero: 'https://images.unsplash.com/photo-1565710971154-5ee2fc4a7a15?w=1600&q=80',
};

export const GUIDE_SECTIONS = [
  {
    id: 'getting-started',
    icon: Rocket,
    image: IMG.mobile,
    en: {
      title: 'Getting Started',
      tagline: 'Your first steps with ConcretePulse',
      description: 'ConcretePulse is a concrete delivery dispatch management system. This guide walks you through every module with step-by-step instructions.',
      steps: [
        { title: 'Log In', desc: 'Navigate to the app URL and enter your email and password. If you don\'t have an account, click "Register" to create one. After registering, enter the OTP code sent to your email to verify your account.' },
        { title: 'Understand Your Role', desc: 'Your role (Admin, Dispatcher, or Viewer) determines what you can see and do. Admins have full access, Dispatchers manage operations, and Viewers have read-only access.' },
        { title: 'Navigate the App', desc: 'Use the sidebar on the left to move between modules: Dashboard, Orders, Companies, Locations, Trucks, Drivers, Driver Groups, Reports, and Settings.' },
        { title: 'Switch Language', desc: 'Click the EN/ES toggle in the header to switch between English and Spanish. Your preference is saved automatically.' },
        { title: 'Toggle Dark Mode', desc: 'Go to Settings to switch between light and dark themes. Your preference persists across sessions.' },
        { title: 'Go Mobile', desc: 'ConcretePulse is fully responsive. On mobile, the sidebar collapses into a hamburger menu, and the Kanban board scrolls horizontally with snap-to-column behavior.' },
      ],
      tips: 'New users are assigned the "Viewer" role by default. Ask an Admin to upgrade your role if you need to create or edit data.',
    },
    es: {
      title: 'Primeros Pasos',
      tagline: 'Sus primeros pasos con ConcretePulse',
      description: 'ConcretePulse es un sistema de gestión de despacho de entrega de concreto. Esta guía lo lleva a través de cada módulo con instrucciones paso a paso.',
      steps: [
        { title: 'Iniciar Sesión', desc: 'Navegue a la URL de la aplicación e ingrese su correo y contraseña. Si no tiene cuenta, haga clic en "Registrarse". Después de registrarse, ingrese el código OTP enviado a su correo para verificar su cuenta.' },
        { title: 'Entienda Su Rol', desc: 'Su rol (Administrador, Despachador u Observador) determina lo que puede ver y hacer. Los Administradores tienen acceso completo, los Despachadores gestionan operaciones, y los Observadores tienen acceso de solo lectura.' },
        { title: 'Navegue la App', desc: 'Use la barra lateral izquierda para moverse entre módulos: Panel, Pedidos, Empresas, Ubicaciones, Camiones, Conductores, Grupos, Reportes y Configuración.' },
        { title: 'Cambie de Idioma', desc: 'Haga clic en el interruptor EN/ES en el encabezado para alternar entre inglés y español. Su preferencia se guarda automáticamente.' },
        { title: 'Modo Oscuro', desc: 'Vaya a Configuración para alternar entre temas claro y oscuro. Su preferencia persiste entre sesiones.' },
        { title: 'Versión Móvil', desc: 'ConcretePulse es totalmente responsivo. En móvil, la barra lateral se colapsa en un menú hamburguesa, y el tablero Kanban se desplaza horizontalmente.' },
      ],
      tips: 'Los nuevos usuarios reciben el rol "Observador" por defecto. Pida a un Administrador que actualice su rol si necesita crear o editar datos.',
    },
  },
  {
    id: 'dashboard',
    icon: LayoutDashboard,
    image: IMG.kanban,
    en: {
      title: 'Dispatch Dashboard',
      tagline: 'Command center for real-time operations',
      description: 'The Dashboard is your operational hub. It features a live Kanban board, stat cards, fleet sidebar, map view, filter bar, and action buttons for creating orders and managing deliveries.',
      steps: [
        { title: 'Read the Stat Cards', desc: 'At the top of the Dashboard, four stat cards summarize your operation: Total Orders, Active Deliveries (New + Assigned + In Progress), Trucks Available, and Today Delivered. These update in real time as data changes.' },
        { title: 'Read the Kanban Board', desc: 'Orders flow left to right across four columns with color-coded top borders: New (orange) → Assigned (blue) → In Progress (amber) → Delivered (green). Each card shows the order number, company, location, mix type, volume, assigned truck plate + driver, and scheduled time.' },
        { title: 'Watch ETA Countdowns', desc: 'In-progress order cards display an amber ETA countdown timer showing time remaining until expected delivery, based on historical average delivery times for that location. If overdue, the timer turns red.' },
        { title: 'Create a New Order', desc: 'Click the "New Order" button (orange, top-left). Fill in the company, delivery location, mix type, volume, priority, and scheduled time, then click "Create". The order appears in the New column instantly.' },
        { title: 'Assign a Truck & Driver', desc: 'Click any order card to open the detail modal. In the Assignment section, select an available truck and driver from the dropdowns, then click "Assign". The order moves to the "Assigned" column and the truck status changes to "Loading".' },
        { title: 'Broadcast to WhatsApp', desc: 'In the order detail or new order modal, click "Broadcast to Drivers". Select a driver group, and the system simulates a WhatsApp group chat. The first driver to reply "YES" is automatically assigned.' },
        { title: 'Start Delivery', desc: 'Once assigned, click "Start Delivery" in the order detail modal to move the order to "In Progress". This records the departure time, sets the truck status to "In Transit", and starts the ETA countdown.' },
        { title: 'Mark as Delivered', desc: 'Open an in-progress order and click "Mark Delivered" to complete it. For batch confirmation, use the checkbox in the top-right corner of each card to select multiple orders, then click "Mark Delivered" in the green bulk-action bar that appears.' },
        { title: 'Use Demo Mode', desc: 'Toggle "Demo Mode" (violet button, top-right) to auto-progress orders every 6 seconds. It auto-assigns new orders, advances assigned → in-progress, and completes in-progress → delivered. Perfect for presentations and training — a violet banner confirms it is active.' },
        { title: 'Simulate WhatsApp Order', desc: 'Click the "Simulate Client WhatsApp" button (chat icon) to generate a random incoming order as if a client sent it via WhatsApp. Requires at least one company and location to exist.' },
        { title: 'Simulate Driver Reply', desc: 'Click the "Simulate Driver Reply" button (reply icon) to auto-assign the first new order to a random available truck and driver — as if a driver replied "YES" to a broadcast.' },
        { title: 'Filter the Board', desc: 'Use the filter bar below the stat cards: click status chips (All, Active, New, Assigned, In Progress, Delivered) with live order counts, or use the Truck and Company dropdowns to narrow further. Click "Clear" to reset all filters.' },
        { title: 'Check the Fleet Sidebar', desc: 'On the right side of the board, the Truck & Driver sidebar shows a live summary of all trucks and drivers with their current status. Use it to see who is available before assigning.' },
        { title: 'View the Active Map', desc: 'Below the Kanban board, the map placeholder shows the location of active trucks. This gives a geographic overview of your fleet in transit.' },
      ],
      tips: 'Urgent orders appear with a red "URGENT" badge and a warning triangle icon. Use the priority flag when creating orders to surface critical deliveries at the top of each column.',
    },
    es: {
      title: 'Panel de Despacho',
      tagline: 'Centro de comando para operaciones en tiempo real',
      description: 'El Panel es su centro operativo. Cuenta con un tablero Kanban en vivo, tarjetas de estadísticas, barra lateral de flota, vista de mapa, barra de filtros y botones de acción para crear pedidos y gestionar entregas.',
      steps: [
        { title: 'Lea las Tarjetas de Estadísticas', desc: 'En la parte superior del Panel, cuatro tarjetas resumen su operación: Total de Pedidos, Entregas Activas (Nuevas + Asignadas + En Progreso), Camiones Disponibles y Entregados Hoy. Se actualizan en tiempo real.' },
        { title: 'Lea el Tablero Kanban', desc: 'Los pedidos fluyen de izquierda a derecha en cuatro columnas con bordes superiores de color: Nuevo (naranja) → Asignado (azul) → En Progreso (ámbar) → Entregado (verde). Cada tarjeta muestra número, empresa, ubicación, mezcla, volumen, placa del camión + conductor y hora.' },
        { title: 'Vea los Contadores ETA', desc: 'Las tarjetas en progreso muestran un contador ETA ámbar con el tiempo restante hasta la entrega esperada, basado en tiempos históricos de esa ubicación. Si está vencido, el contador se pone rojo.' },
        { title: 'Cree un Pedido Nuevo', desc: 'Haga clic en "Nuevo Pedido" (naranja, arriba a la izquierda). Complete empresa, ubicación, tipo de mezcla, volumen, prioridad y hora programada, luego haga clic en "Crear".' },
        { title: 'Asigne Camión y Conductor', desc: 'Haga clic en cualquier tarjeta para abrir el modal de detalle. En la sección de Asignación, seleccione un camión y conductor disponibles, luego haga clic en "Asignar". El pedido pasa a "Asignado" y el camión a "Cargando".' },
        { title: 'Transmita por WhatsApp', desc: 'En el modal de detalle o nuevo pedido, haga clic en "Transmitir a Conductores". Seleccione un grupo y el sistema simula un chat de WhatsApp. El primer conductor en responder "SÍ" es asignado automáticamente.' },
        { title: 'Inicie la Entrega', desc: 'Una vez asignado, haga clic en "Iniciar Entrega" para mover el pedido a "En Progreso". Esto registra la hora de salida, cambia el camión a "En Tránsito" e inicia el contador ETA.' },
        { title: 'Marque como Entregado', desc: 'Abra un pedido en progreso y haga clic en "Marcar Entregado". Para confirmación masiva, use la casilla en la esquina superior derecha de cada tarjeta para seleccionar múltiples pedidos, luego haga clic en "Marcar Entregado" en la barra verde que aparece.' },
        { title: 'Use el Modo Demo', desc: 'Active "Modo Demo" (botón violeta, arriba a la derecha) para progresar pedidos automáticamente cada 6 segundos. Asigna pedidos nuevos, avanza asignados → en progreso, y completa en progreso → entregado. Ideal para presentaciones.' },
        { title: 'Simule Pedido WhatsApp', desc: 'Haga clic en "Simular WhatsApp Cliente" (icono de chat) para generar un pedido aleatorio entrante como si un cliente lo enviara por WhatsApp. Requiere al menos una empresa y ubicación.' },
        { title: 'Simule Respuesta de Conductor', desc: 'Haga clic en "Simular Respuesta Conductor" (icono de respuesta) para auto-asignar el primer pedido nuevo a un camión y conductor disponibles aleatorios.' },
        { title: 'Filtre el Tablero', desc: 'Use la barra de filtros bajo las tarjetas: haga clic en las fichas de estado (Todos, Activos, Nuevos, Asignados, En Progreso, Entregados) con conteos en vivo, o use los menús de Camión y Empresa. Haga clic en "Limpiar" para reiniciar.' },
        { title: 'Revise la Barra Lateral', desc: 'A la derecha del tablero, la barra lateral de Camiones y Conductores muestra un resumen en vivo de todos los camiones y conductores con su estado actual.' },
        { title: 'Vea el Mapa Activo', desc: 'Bajo el tablero Kanban, el mapa muestra la ubicación de los camiones activos. Da una visión geográfica de su flota en tránsito.' },
      ],
      tips: 'Los pedidos urgentes aparecen con una insignia roja "URGENT" y un icono de triángulo de advertencia. Use la bandera de prioridad al crear pedidos para resaltar entregas críticas.',
    },
  },
  {
    id: 'orders',
    icon: Package,
    image: IMG.orderModal,
    en: {
      title: 'Order Management',
      tagline: 'Full lifecycle tracking from pour to proof',
      description: 'The Orders page is a searchable, filterable table of every delivery order. Create new orders, track status history, flag priorities, and cancel with justification.',
      steps: [
        { title: 'Create an Order', desc: 'Click "New Order" and fill in: Company (dropdown of registered companies), Delivery Location (filtered to the selected company\'s sites), Mix Type (210–420 kg/cm²), Volume (m³), Priority (Normal/Urgent), and Scheduled Time.' },
        { title: 'Track the Lifecycle', desc: 'Each order records timestamped milestones: creation, assignment, departure, arrival, and completion. Open any order to see the full timeline.' },
        { title: 'Flag Priority', desc: 'Set priority to "Urgent" when creating or editing an order. Urgent orders show a red badge and sort to the top of the Kanban board.' },
        { title: 'Cancel an Order', desc: 'Only orders in "New" or "Assigned" status can be cancelled. Open the order, click "Cancel", and provide a justification reason. The cancellation is logged with your name and timestamp.' },
        { title: 'Search & Filter', desc: 'Use the search bar to find orders by number or company name. Combine with status and date filters to narrow results. Sort by any column by clicking the column header.' },
      ],
      tips: 'Once an order is "In Progress", it cannot be cancelled — only completed. Make sure to verify all details before starting delivery.',
    },
    es: {
      title: 'Gestión de Pedidos',
      tagline: 'Seguimiento del ciclo completo desde el vaciado hasta la prueba',
      description: 'La página de Pedidos es una tabla buscable y filtrable de cada pedido de entrega. Cree pedidos nuevos, rastree el historial de estados, marque prioridades y cancele con justificación.',
      steps: [
        { title: 'Cree un Pedido', desc: 'Haga clic en "Nuevo Pedido" y complete: Empresa, Ubicación de Entrega (filtrada a los sitios de la empresa), Tipo de Mezcla (210–420 kg/cm²), Volumen (m³), Prioridad y Hora Programada.' },
        { title: 'Rastree el Ciclo', desc: 'Cada pedido registra hitos con marca de tiempo: creación, asignación, salida, llegada y finalización. Abra cualquier pedido para ver la línea de tiempo completa.' },
        { title: 'Marque Prioridad', desc: 'Establezca prioridad en "Urgente" al crear o editar un pedido. Los pedidos urgentes muestran una insignia roja y se ordenan al inicio del Kanban.' },
        { title: 'Cancele un Pedido', desc: 'Solo los pedidos en estado "Nuevo" o "Asignado" pueden cancelarse. Abra el pedido, haga clic en "Cancelar" y proporcione una razón. La cancelación se registra con su nombre y hora.' },
        { title: 'Busque y Filtre', desc: 'Use la barra de búsqueda para encontrar pedidos por número o empresa. Combine con filtros de estado y fecha. Ordene por cualquier columna haciendo clic en el encabezado.' },
      ],
      tips: 'Una vez que un pedido está "En Progreso", no puede cancelarse — solo completarse. Verifique todos los detalles antes de iniciar la entrega.',
    },
  },
  {
    id: 'trucks',
    icon: Truck,
    image: IMG.fleet,
    en: {
      title: 'Fleet Management',
      tagline: 'Know where every mixer is, right now',
      description: 'Manage your entire concrete mixer fleet. Track real-time status, capacity, driver assignments, and maintenance state from one screen.',
      steps: [
        { title: 'View Truck Status', desc: 'Each truck card shows its current state: Available, Loading, In Transit, Maintenance, or Off Duty. Status updates automatically when orders are assigned or completed.' },
        { title: 'Add a Truck', desc: 'Click "Add Truck" and enter the truck ID (e.g. T-01), license plate, capacity (m³), model, and year. Only Admins can create trucks.' },
        { title: 'Check Capacity', desc: 'Each card displays the truck\'s capacity in cubic meters. When assigning an order, match the truck capacity to the order volume to avoid overloading.' },
        { title: 'View Driver Assignment', desc: 'The current driver\'s name appears on each truck card. Driver availability updates in sync — when a truck is "In Transit", the driver shows as "On Route".' },
        { title: 'Edit or Remove Trucks', desc: 'Click any truck to edit its details or change its status. To remove a truck, click the delete button (Admin only). Trucks with active orders cannot be deleted.' },
      ],
      tips: 'Set trucks to "Maintenance" proactively to prevent dispatchers from assigning them to new orders during service intervals.',
    },
    es: {
      title: 'Gestión de Flota',
      tagline: 'Sepa dónde está cada mezcladora, ahora mismo',
      description: 'Gestione toda su flota de mezcladoras. Rastree estado en tiempo real, capacidad, asignación de conductores y estado de mantenimiento desde una pantalla.',
      steps: [
        { title: 'Vea el Estado del Camión', desc: 'Cada tarjeta muestra su estado actual: Disponible, Cargando, En Tránsito, Mantenimiento o Fuera de Servicio. El estado se actualiza automáticamente al asignar o completar pedidos.' },
        { title: 'Agregue un Camión', desc: 'Haga clic en "Agregar Camión" e ingrese ID (ej. T-01), placa, capacidad (m³), modelo y año. Solo los Administradores pueden crear camiones.' },
        { title: 'Verifique la Capacidad', desc: 'Cada tarjeta muestra la capacidad en metros cúbicos. Al asignar un pedido, haga coincidir la capacidad del camión con el volumen del pedido.' },
        { title: 'Vea la Asignación de Conductor', desc: 'El nombre del conductor actual aparece en cada tarjeta. La disponibilidad del conductor se actualiza en sincronía.' },
        { title: 'Edite o Elimine Camiones', desc: 'Haga clic en cualquier camión para editar sus detalles o cambiar su estado. Para eliminar, haga clic en el botón de eliminar (solo Administrador). Los camiones con pedidos activos no pueden eliminarse.' },
      ],
      tips: 'Establezca camiones en "Mantenimiento" proactivamente para evitar que los despachadores los asignen durante intervalos de servicio.',
    },
  },
  {
    id: 'drivers',
    icon: Users,
    image: IMG.drivers,
    en: {
      title: 'Driver Management',
      tagline: 'Workforce visibility and compensation in one place',
      description: 'Track every driver — employees and contractors — with availability status, compensation rates, and license expiry tracking. The Drivers page displays all drivers in a searchable table with inline edit and delete actions.',
      steps: [
        { title: 'Understand the Table Layout', desc: 'The table has columns: Name, Cédula, Phone (hidden on mobile), Type, Availability, Rate/Hour (hidden on small screens), Rate/Order (hidden on small screens), and Actions. Responsive column hiding keeps the table readable on any device.' },
        { title: 'Search for a Driver', desc: 'Use the search bar (top-right, below the page title) to find drivers by name or cédula number. Search filters the table in real time as you type.' },
        { title: 'Add a Driver', desc: 'Click "Add New" (orange button, top-right). In the dialog, enter: full name, cédula (national ID), phone number, type (Employee or Contractor), availability, compensation rates, OT multiplier, and license expiry. Only Admins can create drivers.' },
        { title: 'Set Compensation Rates', desc: 'In the driver form, configure Rate/Hour, Rate/Order, and Rate/Km independently per driver. Set a secondary rate multiplier (e.g. 1.5×) for overtime calculations. These rates feed into the Compensation Calculator when orders are delivered.' },
        { title: 'Track Availability', desc: 'Drivers have four states with color-coded badges: Available (green), On Route (amber), Off Duty (gray), and Vacation (purple). Availability updates automatically as orders are assigned and completed on the Dashboard.' },
        { title: 'Differentiate Employee vs Contractor', desc: 'The Type column shows a blue "Employee" badge or orange "Contractor" badge. Employees typically use hourly rates; contractors may use per-order or per-km rates.' },
        { title: 'Edit a Driver', desc: 'Click the pencil icon in the Actions column to open the edit dialog. All fields are pre-filled with the driver\'s current data. Only Admins can edit drivers.' },
        { title: 'Delete a Driver', desc: 'Click the trash icon in the Actions column to remove a driver. Only Admins can delete. Exercise caution — deleted drivers cannot be recovered.' },
        { title: 'Monitor License Expiry', desc: 'Store each driver\'s license expiry date in the form. Check regularly to avoid compliance risk — expired licenses should be renewed before the driver returns to active duty.' },
      ],
      tips: 'When calculating compensation from an order\'s detail modal, the system auto-fills driver and order data when an order is marked delivered. Admins can override the calculated amount with a note.',
    },
    es: {
      title: 'Gestión de Conductores',
      tagline: 'Visibilidad de fuerza laboral y compensación en un solo lugar',
      description: 'Rastree cada conductor — empleados y contratistas — con estado de disponibilidad, tarifas de compensación y seguimiento de vencimiento de licencia. La página de Conductores muestra todos los conductores en una tabla buscable con acciones de editar y eliminar.',
      steps: [
        { title: 'Comprenda la Tabla', desc: 'La tabla tiene columnas: Nombre, Cédula, Teléfono (oculto en móvil), Tipo, Disponibilidad, Tarifa/Hora (oculto en pantallas pequeñas), Tarifa/Pedido (oculto en pantallas pequeñas) y Acciones.' },
        { title: 'Busque un Conductor', desc: 'Use la barra de búsqueda (arriba a la derecha, bajo el título) para encontrar conductores por nombre o cédula. El filtro se aplica en tiempo real mientras escribe.' },
        { title: 'Agregue un Conductor', desc: 'Haga clic en "Agregar" (botón naranja, arriba a la derecha). En el diálogo, ingrese: nombre, cédula, teléfono, tipo (Empleado o Contratista), disponibilidad, tarifas, multiplicador de horas extra y vencimiento de licencia. Solo los Administradores pueden crear conductores.' },
        { title: 'Configure Tarifas', desc: 'En el formulario, configure Tarifa/Hora, Tarifa/Pedido y Tarifa/Km independientemente por conductor. Establezca un multiplicador secundario (ej. 1.5×) para horas extra. Estas tarifas alimentan la Calculadora de Compensación.' },
        { title: 'Rastree Disponibilidad', desc: 'Los conductores tienen cuatro estados con insignias de color: Disponible (verde), En Ruta (ámbar), Fuera de Servicio (gris) y Vacaciones (morado). La disponibilidad se actualiza automáticamente al asignar y completar pedidos.' },
        { title: 'Diferencie Empleado vs Contratista', desc: 'La columna Tipo muestra una insignia azul "Empleado" o naranja "Contratista". Los empleados usan tarifa por hora; los contratistas pueden usar tarifa por pedido o por km.' },
        { title: 'Edite un Conductor', desc: 'Haga clic en el icono de lápiz en la columna Acciones para abrir el diálogo de edición. Todos los campos se pre-llenan con los datos actuales. Solo los Administradores pueden editar.' },
        { title: 'Elimine un Conductor', desc: 'Haga clic en el icono de papelera en la columna Acciones para eliminar un conductor. Solo los Administradores pueden eliminar. Tenga precaución — los conductores eliminados no pueden recuperarse.' },
        { title: 'Monitoree Vencimiento de Licencia', desc: 'Almacene la fecha de vencimiento de la licencia en el formulario. Revise regularmente para evitar riesgos de cumplimiento.' },
      ],
      tips: 'Al calcular compensación desde el modal de detalle del pedido, el sistema pre-completa los datos del conductor y pedido al marcar una entrega como completada. Los Administradores pueden ajustar el monto con una nota.',
    },
  },
  {
    id: 'companies',
    icon: Building2,
    image: IMG.companies,
    en: {
      title: 'Client & Company Management',
      tagline: 'Your full client roster with credit intelligence',
      description: 'Manage every construction company you serve. Track contacts, credit status, credit limits, and billing details.',
      steps: [
        { title: 'Add a Company', desc: 'Click "Add Company" and enter: company name, primary contact name, phone, and email. Admins and Dispatchers can create companies.' },
        { title: 'Set Credit Status', desc: 'Choose from four states: Approved, Pending, Suspended, or C.O.D. (Cash on Delivery). The status is visible at order creation to prevent unapproved deliveries.' },
        { title: 'Configure Credit Limit', desc: 'Set a USD credit limit per company to enforce accounts-receivable policy. Track outstanding balances against the limit.' },
        { title: 'Add Billing Contacts', desc: 'Store separate billing contact name, phone, and email for accounts-receivable communication. This keeps operational and billing contacts distinct.' },
        { title: 'Link Delivery Locations', desc: 'Each company links to its registered delivery sites. When creating an order, only locations belonging to the selected company appear in the dropdown.' },
      ],
      tips: 'Set new companies to "Pending" until credit is verified. Only approve after background checks to protect your accounts receivable.',
    },
    es: {
      title: 'Gestión de Clientes y Empresas',
      tagline: 'Su cartera completa de clientes con inteligencia crediticia',
      description: 'Gestione cada empresa constructora a la que atiende. Rastree contactos, estado crediticio, límites de crédito y datos de facturación.',
      steps: [
        { title: 'Agregue una Empresa', desc: 'Haga clic en "Agregar Empresa" e ingrese: nombre, contacto principal, teléfono y correo. Administradores y Despachadores pueden crear empresas.' },
        { title: 'Configure Estado Crediticio', desc: 'Elija entre cuatro estados: Aprobado, Pendiente, Suspendido o Contra Entrega. El estado es visible al crear pedidos.' },
        { title: 'Configure Límite de Crédito', desc: 'Establezca un límite de crédito en USD por empresa para aplicar la política de cuentas por cobrar.' },
        { title: 'Agregue Contactos de Facturación', desc: 'Almacene nombre, teléfono y correo de facturación separadamente para comunicación de cuentas por cobrar.' },
        { title: 'Vincule Ubicaciones', desc: 'Cada empresa se vincula a sus sitios de entrega. Al crear un pedido, solo aparecen las ubicaciones de la empresa seleccionada.' },
      ],
      tips: 'Establezca nuevas empresas en "Pendiente" hasta verificar el crédito. Solo apruebe después de verificaciones para proteger sus cuentas por cobrar.',
    },
  },
  {
    id: 'locations',
    icon: MapPin,
    image: IMG.locations,
    en: {
      title: 'Delivery Locations',
      tagline: 'Smart job sites with mix restrictions & ETA intelligence',
      description: 'Each delivery location stores an address, GPS coordinates, allowed concrete mixes, special instructions, and historical delivery time data.',
      steps: [
        { title: 'Add a Location', desc: 'Click "Add Location" and enter: location name, linked company, and address. Use the interactive map picker to set GPS coordinates by clicking on the map.' },
        { title: 'Set Allowed Mixes', desc: 'Define which concrete strengths (210–420 kg/cm²) are permitted at each site. When creating an order, only allowed mixes appear in the dropdown — preventing spec errors.' },
        { title: 'Add Special Instructions', desc: 'Store site-specific notes: access codes, unloading procedures, on-site contacts, gate hours. These instructions travel with every order to that location.' },
        { title: 'View Historical ETA', desc: 'The system automatically calculates average delivery time from past orders to the same location. This ETA is shown when scheduling new pours.' },
        { title: 'Use the Map Picker', desc: 'When creating a location, click anywhere on the Leaflet map to set coordinates. Search for an address to center the map, then fine-tune by clicking.' },
      ],
      tips: 'Keep special instructions updated — access codes change, gates get locked, and site contacts rotate. Outdated instructions cause delivery delays.',
    },
    es: {
      title: 'Ubicaciones de Entrega',
      tagline: 'Sitios de obra inteligentes con restricciones de mezcla e inteligencia ETA',
      description: 'Cada ubicación almacena dirección, coordenadas GPS, mezclas permitidas, instrucciones especiales y datos históricos de tiempo de entrega.',
      steps: [
        { title: 'Agregue una Ubicación', desc: 'Haga clic en "Agregar Ubicación" e ingrese: nombre, empresa vinculada y dirección. Use el mapa interactivo para establecer coordenadas GPS.' },
        { title: 'Configure Mezclas Permitidas', desc: 'Defina qué resistencias de concreto (210–420 kg/cm²) están permitidas en cada sitio. Al crear pedidos, solo aparecen las mezclas permitidas.' },
        { title: 'Agregue Instrucciones Especiales', desc: 'Almacene notas del sitio: códigos de acceso, procedimientos de descarga, contactos, horarios. Estas instrucciones viajan con cada pedido.' },
        { title: 'Vea el ETA Histórico', desc: 'El sistema calcula automáticamente el tiempo promedio de entrega de pedidos anteriores a la misma ubicación. Este ETA se muestra al programar nuevos vaciados.' },
        { title: 'Use el Selector de Mapa', desc: 'Al crear una ubicación, haga clic en cualquier punto del mapa Leaflet para establecer coordenadas. Busque una dirección para centrar el mapa.' },
      ],
      tips: 'Mantenga las instrucciones especiales actualizadas — los códigos de acceso cambian, las puertas se bloquean y los contactos rotan. Las instrucciones obsoletas causan retrasos.',
    },
  },
  {
    id: 'reports',
    icon: BarChart2,
    image: IMG.analytics,
    en: {
      title: 'Analytics Dashboard',
      tagline: 'Interactive dashboards that drive better decisions',
      description: 'A full analytics suite with date-range filters, trend charts, status distribution, and per-entity breakdowns. Export to CSV or PDF.',
      steps: [
        { title: 'Use the Global Filter Bar', desc: 'At the top of the Reports page, select a date range using quick presets (7/30/90 days, this month, all time). Optionally filter by company or driver. Filters apply across all tabs instantly.' },
        { title: 'Explore the Overview Tab', desc: 'View summary stat cards (total orders, volume, completion rate, fleet utilization), a daily delivery trend area chart, a status distribution donut chart, and a mix type bar chart.' },
        { title: 'Analyze Customers', desc: 'The Customers tab shows per-company breakdowns: delivery counts, volumes, cancellation rates. A horizontal bar chart compares companies visually.' },
        { title: 'Analyze Locations', desc: 'The Locations tab shows average delivery time per location. Sort by time, order count, or volume to identify slow routes and top performers.' },
        { title: 'Analyze Drivers', desc: 'The Drivers tab shows per-driver order counts, hours worked, and volume delivered. A league table ranks drivers by deliveries completed.' },
        { title: 'Analyze Trucks', desc: 'The Trucks tab shows fleet utilization, delivery counts per truck, and maintenance status distribution.' },
        { title: 'Export to CSV', desc: 'Click the "CSV" button on any tab to download the current data as a spreadsheet-ready CSV file. Opens directly in Excel or Google Sheets.' },
        { title: 'Export to PDF', desc: 'Click "PDF" to generate a formatted PDF report. Available for daily dispatch, delivery history, and driver performance. Restricted to Admin and Dispatcher roles.' },
      ],
      tips: 'Use the date-range presets to compare periods — for example, set "30 days" to see the last month, then switch to "This Month" to compare against the current period.',
    },
    es: {
      title: 'Panel de Analítica',
      tagline: 'Tableros interactivos que impulsan mejores decisiones',
      description: 'Una suite completa de analítica con filtros de rango de fechas, gráficos de tendencia, distribución de estados y desgloses por entidad. Exporte a CSV o PDF.',
      steps: [
        { title: 'Use la Barra de Filtros', desc: 'En la parte superior de Reportes, seleccione un rango de fechas con presets rápidos (7/30/90 días, este mes, todo). Opcionalmente filtre por empresa o conductor. Los filtros se aplican en todas las pestañas.' },
        { title: 'Explore la Pestaña General', desc: 'Vea tarjetas de resumen (pedidos totales, volumen, tasa de finalización, uso de flota), gráfico de tendencia diaria, dona de distribución de estados y barras de tipos de mezcla.' },
        { title: 'Analice Clientes', desc: 'La pestaña Clientes muestra desgloses por empresa: recuentos de entrega, volúmenes, tasas de cancelación. Un gráfico de barras compara empresas visualmente.' },
        { title: 'Analice Ubicaciones', desc: 'La pestaña Ubicaciones muestra el tiempo promedio de entrega por ubicación. Ordene por tiempo, recuento o volumen para identificar rutas lentas.' },
        { title: 'Analice Conductores', desc: 'La pestaña Conductores muestra pedidos por conductor, horas trabajadas y volumen entregado. Una tabla clasifica a los conductores por entregas completadas.' },
        { title: 'Analice Camiones', desc: 'La pestaña Camiones muestra uso de flota, recuentos de entrega por camión y distribución de estados de mantenimiento.' },
        { title: 'Exporte a CSV', desc: 'Haga clic en "CSV" en cualquier pestaña para descargar los datos actuales como archivo CSV. Se abre directamente en Excel o Google Sheets.' },
        { title: 'Exporte a PDF', desc: 'Haga clic en "PDF" para generar un reporte PDF formateado. Disponible para despacho diario, historial de entregas y desempeño de conductores. Restringido a Administrador y Despachador.' },
      ],
      tips: 'Use los presets de rango de fechas para comparar períodos — por ejemplo, establezca "30 días" para ver el último mes, luego cambie a "Este Mes" para comparar.',
    },
  },
  {
    id: 'driver-groups',
    icon: UserCog,
    image: IMG.groups,
    en: {
      title: 'Driver Groups',
      tagline: 'Organize drivers into broadcast-ready teams',
      description: 'Create logical driver groups by shift, zone, or contractor pool. Broadcast orders to specific groups and let the first-reply system auto-assign.',
      steps: [
        { title: 'Create a Group', desc: 'Go to Driver Groups and click "Add Group". Enter a name (e.g. Night Shift, North Zone) and description, then select drivers to add to the group.' },
        { title: 'Edit Group Members', desc: 'Click any group to add or remove drivers. Changes take effect immediately — the next broadcast will use the updated roster.' },
        { title: 'Broadcast to a Group', desc: 'When broadcasting an order from the Dashboard, select a driver group from the dropdown. Only drivers in that group receive the WhatsApp-style message.' },
        { title: 'First-Reply Assignment', desc: 'In the broadcast modal, drivers appear to reply in a simulated chat. The first driver to reply "YES" is automatically locked in — no dispatcher intervention needed.' },
        { title: 'Auto-Escalation', desc: 'If no driver in the group responds within the timeout, the system can escalate to all available drivers to ensure the order gets covered.' },
      ],
      tips: 'Create groups by zone to minimize drive time — drivers assigned to orders near their usual area complete deliveries faster.',
    },
    es: {
      title: 'Grupos de Conductores',
      tagline: 'Organice conductores en equipos listos para transmisión',
      description: 'Cree grupos lógicos de conductores por turno, zona o pool de contratistas. Transmita pedidos a grupos específicos y deje que el sistema asigne automáticamente.',
      steps: [
        { title: 'Cree un Grupo', desc: 'Vaya a Grupos de Conductores y haga clic en "Agregar Grupo". Ingrese nombre (ej. Turno Nocturno, Zona Norte) y descripción, luego seleccione conductores.' },
        { title: 'Edite Miembros', desc: 'Haga clic en cualquier grupo para agregar o remover conductores. Los cambios surten efecto inmediatamente.' },
        { title: 'Transmita a un Grupo', desc: 'Al transmitir un pedido desde el Panel, seleccione un grupo de conductores. Solo los conductores de ese grupo reciben el mensaje estilo WhatsApp.' },
        { title: 'Asignación al Primer en Responder', desc: 'En el modal de transmisión, los conductores parecen responder en un chat simulado. El primero en responder "SÍ" es asignado automáticamente.' },
        { title: 'Escalamiento Automático', desc: 'Si ningún conductor del grupo responde en el tiempo de espera, el sistema puede escalar a todos los conductores disponibles.' },
      ],
      tips: 'Cree grupos por zona para minimizar el tiempo de conducción — los conductores asignados a pedidos cercanos a su área habitual completan entregas más rápido.',
    },
  },
  {
    id: 'settings',
    icon: Settings,
    image: IMG.settings,
    en: {
      title: 'Settings & Preferences',
      tagline: 'Personalize your workspace',
      description: 'Manage your profile, theme, language, and user invitations. Admins can manage the full user roster.',
      steps: [
        { title: 'Toggle Dark Mode', desc: 'On the Settings page, switch between Light and Dark themes. Your preference is saved per user and applied on every login.' },
        { title: 'Switch Language', desc: 'Change between English and Spanish. The entire interface updates instantly. You can also toggle from the header EN/ES switch.' },
        { title: 'Update Profile', desc: 'Edit your full name and contact details. Changes are saved to your user record immediately.' },
        { title: 'Invite Users (Admin Only)', desc: 'Admins can invite new team members by email. Assign a role (Admin, Dispatcher, or Viewer) when sending the invitation. The invitee receives an email to complete registration.' },
        { title: 'Manage Roles', desc: 'User roles determine access levels. Only Admins can invite new users or change roles. Regular users can invite others as "Viewer" only.' },
      ],
      tips: 'Set your language and theme preferences once — they persist across devices and sessions. No need to reconfigure on each login.',
    },
    es: {
      title: 'Configuración y Preferencias',
      tagline: 'Personalice su espacio de trabajo',
      description: 'Gestione su perfil, tema, idioma e invitaciones de usuarios. Los Administradores pueden gestionar el roster completo.',
      steps: [
        { title: 'Modo Oscuro', desc: 'En Configuración, alterne entre temas Claro y Oscuro. Su preferencia se guarda por usuario y se aplica en cada inicio de sesión.' },
        { title: 'Cambie Idioma', desc: 'Cambie entre inglés y español. Toda la interfaz se actualiza al instante. También puede alternar desde el interruptor EN/ES del encabezado.' },
        { title: 'Actualice Perfil', desc: 'Edite su nombre completo y datos de contacto. Los cambios se guardan inmediatamente.' },
        { title: 'Invite Usuarios (Solo Admin)', desc: 'Los Administradores pueden invitar nuevos miembros por correo. Asigne un rol al enviar la invitación. El invitado recibe un correo para completar el registro.' },
        { title: 'Gestione Roles', desc: 'Los roles determinan los niveles de acceso. Solo los Administradores pueden invitar o cambiar roles. Los usuarios regulares solo pueden invitar como "Observador".' },
      ],
      tips: 'Configure su idioma y tema una vez — persisten entre dispositivos y sesiones. No necesita reconfigurar en cada inicio de sesión.',
    },
  },
  {
    id: 'rbac',
    icon: Shield,
    image: null,
    en: {
      title: 'Role-Based Access Control',
      tagline: 'The right people have the right access',
      description: 'ConcretePulse ships with three pre-configured roles. Every action in the system is gated to ensure security and accountability.',
      steps: [
        { title: 'Admin Role', desc: 'Full read/write access to all modules. Can export PDF and CSV reports, manage users and roles, override driver compensation, view financial data, and delete records.' },
        { title: 'Dispatcher Role', desc: 'Can create and assign orders, broadcast to driver WhatsApp, mark orders delivered, view fleet and driver status, and export reports. Cannot manage users or delete records.' },
        { title: 'Viewer Role', desc: 'Read-only access to all modules. Can view the Kanban board, charts, and fleet status. Cannot create, edit, export, or delete anything.' },
        { title: 'Entity-Level Security', desc: 'Access control is enforced at the database level — not just in the UI. Even if someone bypasses the frontend, the backend rejects unauthorized operations.' },
      ],
      tips: 'Assign the minimum necessary role. Most users should be Viewers unless they actively dispatch orders.',
    },
    es: {
      title: 'Control de Acceso Basado en Roles',
      tagline: 'Las personas correctas tienen el acceso correcto',
      description: 'ConcretePulse incluye tres roles preconfigurados. Cada acción está controlada para garantizar seguridad y responsabilidad.',
      steps: [
        { title: 'Rol Administrador', desc: 'Acceso completo de lectura/escritura a todos los módulos. Puede exportar reportes PDF y CSV, gestionar usuarios y roles, ajustar compensación, ver datos financieros y eliminar registros.' },
        { title: 'Rol Despachador', desc: 'Puede crear y asignar pedidos, transmitir a WhatsApp, marcar entregas, ver flota y conductores, y exportar reportes. No puede gestionar usuarios ni eliminar registros.' },
        { title: 'Rol Observador', desc: 'Acceso de solo lectura a todos los módulos. Puede ver tablero Kanban, gráficos y estado de flota. No puede crear, editar, exportar ni eliminar.' },
        { title: 'Seguridad a Nivel de Entidad', desc: 'El control de acceso se aplica a nivel de base de datos — no solo en la interfaz. El backend rechaza operaciones no autorizadas.' },
      ],
      tips: 'Asigne el rol mínimo necesario. La mayoría de usuarios deberían ser Observadores a menos que despachen pedidos activamente.',
    },
  },
  {
    id: 'faq',
    icon: HelpCircle,
    image: null,
    en: {
      title: 'Frequently Asked Questions',
      tagline: 'Quick answers to common questions',
      description: 'Common questions and troubleshooting tips.',
      steps: [
        { title: 'How do I reset my password?', desc: 'Click "Forgot Password" on the login page. Enter your email and check your inbox for a reset link. Follow the link to set a new password.' },
        { title: 'Why can\'t I cancel an order?', desc: 'Orders can only be cancelled in "New" or "Assigned" status. Once an order is "In Progress" (truck has departed), it must be completed. This prevents disruption to active deliveries.' },
        { title: 'Why don\'t I see the export buttons?', desc: 'PDF and CSV exports are restricted to Admin and Dispatcher roles. If you\'re a Viewer, you can see charts and tables but cannot export. Ask an Admin to upgrade your role.' },
        { title: 'How does Demo Mode work?', desc: 'Demo Mode auto-progresses orders through the Kanban lifecycle every few seconds. Turn it on from the Dashboard action bar. Perfect for training and presentations — turn it off when done.' },
        { title: 'How are delivery ETAs calculated?', desc: 'The system averages the completion times of all past orders to the same delivery location. More historical data means more accurate ETAs.' },
        { title: 'Can I use ConcretePulse on mobile?', desc: 'Yes — the app is fully responsive. The sidebar collapses into a hamburger menu, and the Kanban board scrolls horizontally with touch-friendly snap behavior.' },
      ],
      tips: 'Still stuck? Contact your system administrator or refer to the Product Brief page for a high-level overview of all features.',
    },
    es: {
      title: 'Preguntas Frecuentes',
      tagline: 'Respuestas rápidas a preguntas comunes',
      description: 'Preguntas comunes y consejos de solución de problemas.',
      steps: [
        { title: '¿Cómo restablezco mi contraseña?', desc: 'Haga clic en "Olvidé mi contraseña" en la página de inicio de sesión. Ingrese su correo y revise su bandeja para el enlace de restablecimiento.' },
        { title: '¿Por qué no puedo cancelar un pedido?', desc: 'Los pedidos solo pueden cancelarse en estado "Nuevo" o "Asignado". Una vez "En Progreso", debe completarse para evitar interrupciones.' },
        { title: '¿Por qué no veo los botones de exportación?', desc: 'Las exportaciones PDF y CSV están restringidas a roles de Administrador y Despachador. Si es Observador, puede ver tableros pero no exportar.' },
        { title: '¿Cómo funciona el Modo Demo?', desc: 'El Modo Demo progresa pedidos automáticamente por el ciclo Kanban cada pocos segundos. Actívelo desde el Panel. Ideal para capacitación — desactívelo al terminar.' },
        { title: '¿Cómo se calculan los ETAs de entrega?', desc: 'El sistema promedia los tiempos de finalización de todos los pedidos anteriores a la misma ubicación. Más datos históricos significan ETAs más precisos.' },
        { title: '¿Puedo usar ConcretePulse en móvil?', desc: 'Sí — la app es totalmente responsiva. La barra lateral se colapsa en un menú hamburguesa y el Kanban se desplaza horizontalmente con comportamiento táctil.' },
      ],
      tips: '¿Aún con problemas? Contacte a su administrador del sistema o consulte la página de Documento del Producto para una visión general.',
    },
  },
];